# Generated by Django 3.1.5 on 2021-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210202_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advater',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
