# Generated by Django 3.1.5 on 2021-02-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_customer_advater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='advater',
            field=models.ImageField(blank=True, default='girl.png', null=True, upload_to=''),
        ),
    ]
